employee/urls.py
from django.conf.urls.defaults import *

from views import *

urlpatterns = patterns('employee.views',
	  url(r'^$', 'login', name='login')
	, url(r'^logout/$', 'logout', name='logout')
	, url(r'^authenticate/$', 'authenticate', name='authenticate')
	, url(r'^edit-profile/$', 'edit_profile', name='edit_profile') 
	, url(r'^edit-profile/save/$', 'save_profile', name='save_profile') 
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
	  (r'^admin/', include(admin.site.urls))
	, (r'^admin/doc/', include('django.contrib.admindocs.urls'))
	, (r'^', include('employee.urls'))
	, (r'^menu/', include('menu.urls'))
	, (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', { 'url': '/static/images/favicon.ico' }),
)

if settings.LOCAL:
	urlpatterns += patterns('', (r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }))

employee/models.py
from datetime import datetime

from django.db import models

class Employee(models.Model):
	username = models.CharField(max_length=255, editable=False)
	full_name = models.CharField(max_length=255, help_text='Orders will be placed under this name')
	allergies = models.CharField(blank=True, max_length=255)
	diet = models.TextField(blank=True)
	card_number = models.CharField(blank=True, max_length=255)
	pub_date = models.DateTimeField(auto_now_add=True, editable=False)

	def __unicode__(self):
		return self.full_name
	

employee/forms.py
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError

from models import *

class LoginForm(forms.Form):
	username = forms.CharField(label='Username', error_messages={ 'required': 'Enter your username' })
	password = forms.CharField(label='Password', widget=forms.PasswordInput, error_messages={ 'required': 'Enter your password' })
	
	def ldap_check(self):
		ldap_result = { 'username': 'abrahamalrajhi@gmail.com', 'full_name': 'Ibrahim Al-Rajhi' }
		if not ldap_result: 
			self._errors['username'] = self.error_class(['Username and password don\'t match'])
		else:
			self.cleaned_data['full_name'] = ldap_result['full_name']

	def clean(self, *args, **kwargs):
		self.ldap_check()
		return super(LoginForm, self).clean(*args, **kwargs)


class EditEmployeeForm(ModelForm):
	class Meta:
		model = Employee
		exclude = ['full_name']

employee/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from decorators import *
from forms import *
from models import *

def login(request, prev_login_form=None):
	if 'employee_id' in request.session:
		HttpResponseRedirect(reverse('todays_menu'))
	login_form = (prev_login_form if prev_login_form else LoginForm())
	return render_to_response('login.html', { 'login_form': login_form }, context_instance=RequestContext(request))

@employee_required
def logout(request, **kwargs):
	del request.session['employee_id']
	return HttpResponseRedirect(reverse('login'))

@post_required('login')
def authenticate(request):
	login_form = LoginForm(request.POST)
	if not login_form.is_valid():
		return login(request, login_form)
	else:
		employee = Employee.objects.get_or_create(username=login_form.cleaned_data['username'], defaults={ 'full_name': login_form.cleaned_data['full_name'] })
		result = { 'employee_id': employee[0].pk, 'is_new': employee[1] }
		request.session['employee_id'] = result['employee_id']
		redirect_url = (reverse('edit_profile') if result['is_new'] else reverse('todays_menu'))
		return HttpResponseRedirect(redirect_url)

@employee_required
def edit_profile(request, prev_employee_form=None, **kwargs):
	employee_form = (prev_employee_form if prev_employee_form else EditEmployeeForm(instance=kwargs['employee']))
	return render_to_response('edit_profile.html', { 'employee_form': employee_form }, context_instance=RequestContext(request))

@employee_required
@post_required('edit_profile')
def save_profile(request, **kwargs):
	employee_form = EditEmployeeForm(request.POST, instance=kwargs['employee'])
	if employee_form.is_valid():
		employee_form.save()
		request.session['success_message'] = '<strong>Saved!</strong> Your profile\'s changes have been recorded.'
		return HttpResponseRedirect(reverse('todays_menu'))
	else:
		return edit_profile(request, employee_form)

templates/employee/edit_profile.html
{% extends "client.html" %}    
{% block title %}- Editing Profile{% endblock %}
{% block size %}medium{% endblock %}

{% block content %}

    <div class="inner">
        <h2>Editing Profile</h2>
        <form method="post" class="profile" action="{% url employee.views.save_profile %}">
            {% csrf_token %}   
            <p>
                <label for="id_allergies">List of Allergies <span class="errors">{% for error in employee_form.allergies.errors %} {{ error }} {% endfor %}</span></label>
                {{ employee_form.allergies }}
            </p>
            <p>
                <label for="id_card_number">Card Number <span class="errors">{% for error in employee_form.card_number.errors %} {{ error }} {% endfor %}</span></label>
                {{ employee_form.card_number }}
            </p>
            <p>
                <label for="id_diet">Dietary Restrictions <span class="errors">{% for error in employee_form.diet.errors %} {{ error }} {% endfor %}</span></label>
                {{ employee_form.diet }}
            </p>
            <div class="buttons">
                <button type="submit" class="green thinandtall">
                    <div><span>Save Changes</span></div>
                </button>
            </div>
        </form>
    </div>
    
{% endblock %}

templates/employee/login.html
{% extends "client.html" %}    
{% block title %}- Login to Order{% endblock %}
{% block size %}small{% endblock %}
{% block navigation %}{% endblock %}

{% block content %}

    <form method="post" class="login inner" action="{% url employee.views.authenticate %}">
        {% csrf_token %}   
        <p>
            <label for="id_username">{{ login_form.username.label }} <span class="errors">{% for error in login_form.username.errors %} {{ error }} {% endfor %}</span></label>
            {{ login_form.username }}
        </p>
        <p>
            <label for="id_password">{{ login_form.password.label }} <span class="errors">{% for error in login_form.password.errors %} {{ error }} {% endfor %}</span></label>
            {{ login_form.password }}
        </p>
        <div class="buttons">
            <button type="submit" class="green thinandtall">
                <div><span>Login</span></div>
            </button>
        </div>
    </form>

{% endblock %}