menu/urls.py
from django.conf.urls.defaults import *

from views import *

urlpatterns = patterns('menu.views',
	  url(r'^todays/$', 'todays_menu', name='todays_menu') 
	, url(r'^todays/create/(?P<menu_id>\d+)/$', 'create_order', name='create_order')
	, url(r'^todays/confirm/(?P<order_id>\d+)/$', 'confirm_order', name='confirm_order')
	, url(r'^todays/cancel/(?P<order_id>\d+)/$', 'cancel_order', name='cancel_order')
	, url(r'^menu-list/$', 'menu_list', name='menu_list')
	, url(r'^menu-list/(?P<menu_id>\d+)/$', 'order_list', name='order_list')
	, url(r'^menu-list/(?P<menu_id>\d+)/get-orders/$', 'get_orders', name='get_orders')
	, url(r'^menu-list/(?P<menu_id>\d+)/fulfill-orders/$', 'fulfill_orders', name='fulfill_orders')
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
	  (r'^admin/', include(admin.site.urls))
	, (r'^admin/doc/', include('django.contrib.admindocs.urls'))
	, (r'^', include('employee.urls'))
	, (r'^menu/', include('menu.urls'))
	, (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', { 'url': '/static/images/favicon.ico' }),
)

if settings.LOCAL:
	urlpatterns += patterns('', (r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }))

menu/models.py
from datetime import date, time, datetime, timedelta

from django.db import models
from django.contrib.contenttypes import generic
from django.template.defaultfilters import date as date_filter
from django.template.defaultfilters import timeuntil

from employee.models import Employee

MENU_TYPES = (
	  ('b', 'breakfast')
	, ('l', 'lunch')
	, ('d', 'dinner')
)

ORDER_STATE = (
	  ('c', 'confirmed')
	, ('p', 'placed')
	, ('f', 'fulfilled')
)

CONFIRM_DELTA = 20

def relative_time(time):
	return datetime.combine(date.today(), time)

class Timeslot(models.Model):
	time = models.TimeField(help_text='Must be in <strong>HH:MM</strong> format; for example, 6:30 p.m. would be written as 18:30.')  
	capacity = models.PositiveIntegerField(blank=True, null=True, help_text='An optional limit of employees this timeslot can serve; leave blank to serve an unlimited number of employees.') 

	def availableCountFor(self, menu):
		from menu.models import Order 
		if self.capacity != None:
			used_slots = len(Order.objects.filter(menu=menu, timeslot=self))
			return self.capacity - used_slots

	def isAvailableFor(self, menu):
		return (self.availableCountFor(menu) > 0 if self.capacity != None else True)

	def getFormattedTime(self):
		return date_filter(relative_time(self.time), 'g:i a')

	def getFieldName(self, menu):
		field_name = self.getFormattedTime()
		if self.isAvailableFor(menu):
			if self.capacity != None:
				field_name = '{0} ({1} available slots)'.format(field_name, self.availableCountFor(menu))
			else:
				field_name = '{0} (unlimited)'.format(field_name)
		else:
			field_name = '{0} (FULL)'.format(field_name)
		return field_name

	def __unicode__(self):
		if self.capacity != None:
			return u'{0} ({1} slot capacity)'.format(self.getFormattedTime(), self.capacity)
		else:
			return u'{0} (unlimited)'.format(self.getFormattedTime())


class Meal(models.Model):
	name = models.CharField(max_length=255)
	description = models.TextField()

	def getFieldName(self, menu=None):
		return '{0} - {1}'.format(self.name, self.description)

	def __unicode__(self):
		return self.name


def tryGetMenu(type, publish_date):
	try:
		menu = Menu.objects.filter(type=type, publish_date=publish_date)[0]
	except IndexError:
		return False
	else:
		return menu

class MenuManager(models.Manager):
	def todaysMenus(self, employee):
		todays_menus = []
		for type, typename in MENU_TYPES:
			menu = tryGetMenu(type, date.today())
			order = (menu.getOrderFor(employee) if menu else False)
			stats = (menu.getStats() if menu else False)
			todays_menus.append({ 'typename': typename.capitalize(), 'menu': menu, 'order': order, 'stats': stats }) 	
		return todays_menus

	def pastMenus(self, start_date=datetime.today(), count=15):
		days = []
		for i in xrange(count):
			curdate = start_date - timedelta(days=i)
			datename = date_filter(curdate, 'F j, Y')
			empty = True
			menus = []

			for type, typename in MENU_TYPES:
				menu = tryGetMenu(type, curdate)
				if menu:
					empty = False
					unfulfilled_count = menu.getOrdersWithState('c')
					confirmed_count = menu.getOrdersWithState('f') + unfulfilled_count
					placed_count = menu.getOrdersWithState('p') + confirmed_count
					menus.append({
						  'menu': menu
						, 'placed_count': placed_count
						, 'confirmed_count': confirmed_count
						, 'unfulfilled_count': unfulfilled_count
					})
			days.append({ 'datename': datename, 'menus': menus, 'empty': empty })
		return days


class Menu(models.Model):
	type = models.CharField(max_length=1, choices=MENU_TYPES)
	meals = models.ManyToManyField(Meal)
	timeslots = models.ManyToManyField(Timeslot)
	description = models.TextField(blank=True);
	publish_date = models.DateField(help_text='The day this menu will be available.')
	publish_time = models.TimeField(blank=True, null=True, help_text='An optional time when this menu will be available at. Must be in <strong>HH:MM</strong> format; for example, 6:30 p.m. would be written as 18:30.')
	end_time = models.TimeField(help_text='The time when this menu will expire and become unavailable. Must be in <strong>HH:MM</strong> format; for example, 6:30 p.m. would be written as 18:30.')

	objects = models.Manager()
	managed = MenuManager()

	def hasTimeslot(self, timeslot):
		timeslots = self.timeslots.filter(pk=timeslot.pk)
		return len(timeslots) > 0

	def hasMeal(self, meal):
		meals = self.meals.filter(pk=meal.pk)
		return len(meals) > 0

	def hasOrderFor(self, employee):
		from menu.models import Order
		orders = Order.objects.filter(menu=self, employee=employee)
		return len(orders) > 0

	def getOrderFor(self, employee):
		from menu.models import Order
		if self.hasOrderFor(employee):
			return Order.objects.get(menu=self, employee=employee)
		else:
			return False

	def getOrdersWithState(self, state, count=True):
		orders = Order.objects.filter(menu=self, state=state).order_by('confirm_time')
		return (len(orders) if count else orders)

	def getAllOrders(self):
		orders = []
		for state, statename in ORDER_STATE:
			order = self.getOrdersWithState(state, False)
			if len(order) > 0:
				orders.extend(order)
		return orders

	def getStats(self):
		from menu.models import Order
		try: first_order = Order.objects.filter(menu=self).order_by('confirm_time')[0]
		except IndexError: first_order = False
		empty = True
		meals = []
		for meal in self.meals.all():
			empty = False
			order_count = len(Order.objects.filter(menu=self, meal=meal))
			meals.append({ 'meal': meal, 'order_count': order_count })
		return { 'meals': False if empty else meals, 'first_order': first_order }

	def getTimeuntilEnd(self):
		return timeuntil(datetime.combine(date.today(), self.end_time))

	def endTimeString(self):
		return date_filter(relative_time(self.end_time), 'g:i a')

	def isExpired(self):
		return self.end_time < datetime.time(datetime.now())

	def isPublishable(self):
		publishable_today = (self.publish_date == date.today())
		if self.publish_time:
			return publishable_today and self.publish_time < datetime.time(datetime.now())
		else:
			return publishable_today

	def __unicode__(self):
		return self.get_type_display()


class Order(models.Model):
	employee = models.ForeignKey(Employee)
	menu = models.ForeignKey(Menu)
	meal = models.ForeignKey(Meal)
	timeslot = models.ForeignKey(Timeslot)
	instructions = models.TextField(blank=True)
	state = models.CharField(max_length=1, choices=ORDER_STATE, default='p', editable=False) 
	confirm_time = models.DateTimeField(blank=True, null=True, editable=False)

	def getConfirmableTime(self):
		return relative_time(self.timeslot.time) - timedelta(minutes=CONFIRM_DELTA)

	def confirmableTimeString(self):
		return date_filter(self.getConfirmableTime(), 'g:i a')

	def isConfirmable(self):
		return self.getConfirmableTime() < datetime.now()

	def timesinceConfirmString(self):
		start = self.getConfirmableTime()
		end = self.confirm_time
		return end - start

	def confirm(self):
		if self.isConfirmable():
			self.state = 'c'
			self.confirm_time = datetime.now()
			super(Order, self).save()
			return True
		return False

	def __unicode__(self):
		return '{0} ordered {1}'.format(self.employee, self.meal)

menu/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.widgets import RadioSelect, Select, Textarea
from django.core.exceptions import ValidationError

from models import *

class OrderForm(ModelForm):	
	meal = forms.ModelChoiceField(label='Meal Choices', widget=RadioSelect, queryset=None, empty_label=None)
	timeslot = forms.ModelChoiceField(label='Timeslots', widget=Select, queryset=None, empty_label=None)
	instructions = forms.CharField(label='Special Instructions', widget=Textarea, required=False)

	def __init__(self, target_menu, *args, **kwargs):
		super(OrderForm, self).__init__(*args, **kwargs)
		self.target_menu = target_menu
		self.fields['meal'].queryset = target_menu.meals
		self.fields['timeslot'].queryset = target_menu.timeslots
		self.fields['timeslot'].validators = [self.valid_timeslot]
		self.overwrite_choice_names('meal')
		self.overwrite_choice_names('timeslot')

	def overwrite_choice_names(self, field_name):
		choices = []
		for field_model in self.fields[field_name].queryset.all():
			choices.append((field_model.pk, field_model.getFieldName(self.target_menu)))
		self.fields[field_name].choices = choices

	def valid_timeslot(self, timeslot):
		if not timeslot.isAvailableFor(self.target_menu):
			raise ValidationError('This timeslot is full and unavailable.')

	class Meta:
		model = Order
		fields = ['meal', 'timeslot', 'instructions']

menu/views.py
from datetime import date, datetime

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.contrib import auth
from django.utils import simplejson

from decorators import *
from forms import *
from models import *
from employee.models import *

@employee_required
def todays_menu(request, prev_form=None, **kwargs):
	menus = Menu.managed.todaysMenus(kwargs['employee'])
	for menu_info in menus:
		if menu_info['menu']:
			if prev_form and prev_form.target_menu == menu_info['menu']:
				menu_info['form'] = prev_form
			else:
				menu_info['form'] = OrderForm(menu_info['menu'])
		else:
			menu_info['form'] = False
	return render_to_response('todays_menu.html', { 'menus': menus }, context_instance=RequestContext(request))

@employee_required
@post_required('todays_menu')
def create_order(request, menu_id, **kwargs):
	menu = get_object_or_404(Menu, pk=menu_id)
	new_order = Order(employee=kwargs['employee'], menu=menu)
	order_form = OrderForm(menu, request.POST, instance=new_order)
	if order_form.is_valid():
		order_form.save()
		return HttpResponseRedirect(reverse('todays_menu'))
	else:
		return todays_menu(request, order_form)

@employee_required
def confirm_order(request, order_id, **kwargs):
	order = get_object_or_404(Order, pk=order_id, employee=kwargs['employee'])
	if order.isConfirmable():
		order.confirm()
	return HttpResponseRedirect(reverse('todays_menu'))

@employee_required
def cancel_order(request, order_id, **kwargs):
	order = get_object_or_404(Order, pk=order_id, employee=kwargs['employee'])
	order.delete()
	return HttpResponseRedirect(reverse('todays_menu'))

@staff_required
def menu_list(request):
	days = Menu.managed.pastMenus()
	return render_to_response('menu_list.html', { 'days': days }, context_instance=RequestContext(request))

@staff_required
def order_list(request, menu_id):
	menu = get_object_or_404(Menu, pk=menu_id)
	return render_to_response('order_list.html', { 'menu': menu }, context_instance=RequestContext(request))

@staff_required
def get_orders(request, menu_id):
	menu = get_object_or_404(Menu, pk=menu_id)
	orders = menu.getAllOrders()
	response = [json_order(order) for order in orders]
	return HttpResponse(simplejson.dumps(response), mimetype='application/javascript')

def json_order(order):
	return {
		  'pk': order.pk
		, 'name': order.employee.__unicode__()
		, 'state': order.get_state_display()
		, 'timeslot': order.timeslot.getFormattedTime()
		, 'meal': order.meal.__unicode__()
		, 'instructions': order.instructions
		, 'allergies': order.employee.allergies
		, 'diet': order.employee.diet
	}

@staff_required
@post_required('menu_list')
def fulfill_orders(request, menu_id):
	order_ids = simplejson.loads(request.POST['order_ids'])
	orders = [order_from_id(order_id) for order_id in order_ids]
	response = [change_order_state(order) if order else False for order in orders]
	return HttpResponse(simplejson.dumps(response), mimetype='application/javascript')

def order_from_id(order_id):
	try:
		return Order.objects.get(pk=order_id)
	except DoesNotExist:
		return False
	
def change_order_state(order):
	if order.state != 'f':
		order.state = 'f'
		order.save()
	return order.pk

templates/menu/createMeal.html
<html>
    <form action="/completeOrder" method="get" accept-charset="utf-8"> {% csrf_token %}

    {{ form.as_p }}

    <p><input type="submit" value="Finish &rarr;"0></p>
    </form>
</html>

templates/menu/createMenu.html
<html>

<form action="createMenu_submit" method="get" accept-charset="utf-8">
     
    {{ for meals in allmeals }}

    <p> {{ meals.type }} </p>
    <select name="{{ meals.type }}">
    {% for meal in meals %}
    <option value="{{ meal.id }}"> {{ meal.name }} </option>
    </select>
    {% endfor %}
    {% endfor %}
    
</form>
    

<p><input type="submit" value="Continue &rarr;"0></p>
</form>

</html>

templates/menu/hello.html
<html>
    <h1>
        hello {{ name }} 
    </h1>
</html>

templates/menu/menu_list.html
{% extends "admin.html" %}    
{% block title %}- List of Menus{% endblock %}

{% block content %}

    {% for day in days %} {% if not day.empty %}
        <div class="day">
            <div class="inner">
                <h2>{{ day.datename }}</h2>

                {% for menu_info in day.menus %} 
                    <a href="{% url order_list menu_info.menu.pk %}" class="menu_link">
                        <div class="meta">
                            <div class="block placed"><span>{{ menu_info.placed_count }}</span> placed</div>
                            <div class="block confirmed"><span>{{ menu_info.confirmed_count }}</span> confirmed</div>
                            <div class="block unfulfilled"><span>{{ menu_info.unfulfilled_count }}</span> unfulfilled</div>
                        </div>

                        <div class="title">
                            {{ menu_info.menu }} orders
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    {% endif %} {% endfor %}

{% endblock %}

templates/menu/noMenu.html
{% extends "base.html" %}    
{% block size %}medium{% endblock %}
{% block content %}

<h2> Sorry there is no Menu for today </h2>

{% endblock %}

templates/menu/order_list.html
{% extends "admin.html" %}    
{% block title %}- {{ menu|capfirst }} Orders{% endblock %}

{% block content %}

    <input type="hidden" class="get_orders_url" value="{% url get_orders menu.pk %}" />
    <input type="hidden" class="fulfill_orders_url" value="{% url fulfill_orders menu.pk %}" />

    <div id="controls">
        <div class="right">
            <div class="notice">
            </div>
            <div class="buttons">
                <button class="green thinandtall hidden">
                    <div><span></span></div>
                </button>
                <button class="grey thinandtall">
                    <div><span>Select orders to fulfill</span></div>
                </button>
            </div>
        </div>

        <h1>{{ menu.publish_date }} > {{ menu }} Orders</h1>

        <div class="nav">
            <a href="{% url menu_list %}">Menu List</a>
            <a href="{% url admin:index %}">Admin Panel</a>
        </div>
    </div>

    <div class="order labels">
        <div class="pk"></div>
        <div class="name">Name</div> 
        <div class="state">State</div> 
        <div class="timeslot">Timeslot</div> 
        <div class="meal">Meal Name</div> 
        <div class="instructions">Instructions</div> 
        <div class="allergies">Allergies</div> 
        <div class="diet">Diet Preferences</div> 
    </div>

    <div class="order_list">
        <!-- filled in with ajax responses from 'menu.views.get_orders' -->
    </div>

{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="/static/javascripts/csrf.js"></script>
    <script type="text/javascript" src="/static/javascripts/admin.js"></script>
{% endblock %}

templates/menu/todays_menu.html
{% extends "client.html" %}    
{% block title %}- Place an Order{% endblock %}
{% block size %}medium{% endblock %}

{% block content %}

    {% if success_message %}
        <div class="success message">
            {{ success_message|safe }}
        </div>
    {% endif %}

    {% for menu_info in menus %}
        <div class="menu inner division {% if menu_info.menu.isExpired %}expired{% endif %}">
            <h2>{{ menu_info.typename }} <span class="expiration">has ended</span> {% if menu_info.menu %}<span class="end_time">Ends at {{ menu_info.menu.endTimeString }}</span>{% endif %}</h2>

            {% if not menu_info.menu %}
                <p>A {{ menu_info.typename }} menu has yet to be posted.</p>
            {% else %}
                {% if not menu_info.menu.isPublishable %}
                    <p>A {{ menu_info.typename }} menu will be published at <strong>{{ menu_info.menu.publish_time }}</strong> today.</p>
                {% else %}
                    {% if menu_info.menu.isExpired %}
                        <p>{{ menu_info.typename }} ended at <strong>{{ menu_info.menu.endTimeString }}</strong> today.
                        {% if menu_info.stats %}
                            View some <a class="open_quick_stats" href="">quick stats</a>?</p>

                            <div class="quick_stats">
                                <p>
                                    <strong>Orders:</strong><br/>
                                    {% for meal_info in menu_info.stats.meals %}
                                        {{ meal_info.order_count }} order{{ meal_info.order_count|pluralize:"s" }} for <em>{{ meal_info.meal }}</em>
                                        {% if not forloop.last %}<br/>{% endif %}
                                    {% endfor %}
                                </p>
                                {% if menu_info.stats.first_order %}
                                    <p>
                                        <strong>Trigger Finger:</strong><br/>
                                        {{ menu_info.stats.first_order.employee }} ordered first
                                    </p>
                                {% endif %}
                            </div>
                        {% else %}
                            </p>
                        {% endif %}
                    {% else %}
                        {% if menu_info.order %}
                            <div class="ordered">
                                <h3>
                                    {% if menu_info.order.state == 'p' %}
                                        <h3>Order placed</h3>
                                    {% else %}
                                        {% if menu_info.order.state == 'c' %}
                                            <h3>Order confirmed</h3>
                                        {% else %}
                                            <h3>Order fulfilled</h3>
                                        {% endif %}
                                    {% endif %}
                                </h3>
                                {% if menu_info.order.state == 'c' %}
                                    <p>Your order has been marked as <em>confirmed</em> and is queued up for preparation.</p>
                                {% endif %}
                                <p>
                                    <strong>You ordered:</strong><br/>
                                    {{ menu_info.order.meal.getFieldName }}
                                </p>
                                <p>
                                    <strong>Your instructions are to:</strong><br/>
                                    {% if menu_info.order.instructions %}
                                        {{ menu_info.order.instructions }}
                                    {% else %}
                                        Do nothing special
                                    {% endif %}
                                </p>
                                <p>
                                    <strong>Your timeslot is:</strong><br/>
                                    {{ menu_info.order.timeslot.getFormattedTime }}
                                </p>

                                {% if menu_info.order.state == 'p' %}
                                    <p>
                                        <strong>Your order HAS NOT been confirmed:</strong><br/>
                                        Make sure you come back after <strong>{{ menu_info.order.confirmableTimeString }}</strong> to confirm your order, or your meal <em>will not</em> be prepared. In the meantime, you can still cancel and reorder.
                                    </p>

                                    <div class="buttons">
                                        {% if menu_info.order.isConfirmable %}
                                            <button class="green thinandtall" onclick="location.href='{% url confirm_order menu_info.order.pk %}'">
                                                <div><span>Confirm Order</span></div>
                                            </button>
                                        {% else %}
                                            <button class="inactive thinandtall">
                                                <div><span>Confirm Order @ {{ menu_info.order.confirmableTimeString }}</span></div>
                                            </button>
                                        {% endif %}
                                        <button class="red thinandtall" onclick="location.href='{% url cancel_order menu_info.order.pk %}'">
                                            <div><span>Cancel Order</span></div>
                                        </button>
                                    </div>
                                {% endif %}
                            </div>
                        {% else %}
                            <form method="post" action="{% url create_order menu_info.menu.pk %} ">
                                {% csrf_token %}
                                {% if menu_info.menu.description %} 
                                    <p>{{ menu_info.menu.description }}</p> 
                                {% endif %}
                                <p>
                                    <label for="id_meal">{{ menu_info.form.meal.label }} <span class="errors">{% for error in menu_info.form.meal.errors %} {{ error }} {% endfor %}</span></label>
                                    <div class="radio">{{ menu_info.form.meal }}</div>
                                </p>
                                <p>
                                    <label for="id_timeslot">{{ menu_info.form.timeslot.label }} <span class="errors">{% for error in menu_info.form.timeslot.errors %} {{ error }} {% endfor %}</span></label>
                                    {{ menu_info.form.timeslot }}
                                </p>
                                <p>
                                    <label for="id_instructions">{{ menu_info.form.instructions.label }} <span class="errors">{% for error in menu_info.form.instructions.errors %} {{ error }} {% endfor %}</span></label>
                                    {{ menu_info.form.instructions }}
                                </p>
                                <div class="buttons">
                                    <button type="submit" class="green thinandtall">
                                        <div><span>Place Order</span></div>
                                    </button>
                                </div>
                            </form>
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endif %}

        </div>
    {% endfor %}
{% endblock %}